"""
Compiles a business proposal PDF using the existing LaTeX template.
Copies proposal-business/ into a temp dir, overwrites info + section
files, then runs lualatex twice (needed for TOC page numbers).
"""

import base64
import shutil
import subprocess
import tempfile
from pathlib import Path

PROPOSAL_SRC = Path(__file__).parent.parent / "proposal-business"

_SPECIAL = str.maketrans({
    '\\': r'\textbackslash{}',
    '{': r'\{',
    '}': r'\}',
    '$': r'\$',
    '&': r'\&',
    '#': r'\#',
    '%': r'\%',
    '_': r'\_',
    '^': r'\textasciicircum{}',
    '~': r'\textasciitilde{}',
})

_MIME_EXT = {
    "image/jpeg": "jpg",
    "image/jpg":  "jpg",
    "image/png":  "png",
}

_SECTION_TITLES = {
    "summary":    "Resumo Executivo",
    "problem":    "Descrição do Problema",
    "solution":   "Solução Proposta",
    "investment": "Investimento",
    "terms":      "Termos e Condições",
}

_SECTION_FILES = {
    "summary":    "business-01-summary.tex",
    "problem":    "business-02-problem.tex",
    "solution":   "business-03-solution.tex",
    "investment": "business-04-investment.tex",
    "terms":      "business-05-terms.tex",
}


def _e(v) -> str:
    return str(v).translate(_SPECIAL)


def _fmt_money(value: float, currency: str) -> str:
    s = f"{round(value, 2):.2f}"
    int_s, dec_s = s.split(".")
    int_fmt = f"{int(int_s):,}".replace(",", ".")
    return f"{int_fmt},{dec_s}\\,{_e(currency)}"


def _fmt_qty(qty: float) -> str:
    if qty == int(qty):
        return str(int(qty))
    return f"{qty:.2f}".rstrip("0").replace(".", ",")


def _info_tex(d: dict) -> str:
    return (
        "% Generated by proposal-web\n"
        f"\\newcommand{{\\doctype}}{{{_e(d.get('doctype', 'Proposta Comercial'))}}}\n"
        f"\\newcommand{{\\clientname}}{{{_e(d.get('client_name', ''))}}}\n"
        f"\\newcommand{{\\clientcompany}}{{{_e(d.get('client_company', ''))}}}\n"
        f"\\newcommand{{\\clientaddress}}{{{_e(d.get('client_address', ''))}}}\n"
        f"\\newcommand{{\\clientemail}}{{{_e(d.get('client_email', ''))}}}\n"
        f"\\newcommand{{\\clientphone}}{{{_e(d.get('client_phone', ''))}}}\n"
        f"\\newcommand{{\\proponentname}}{{{_e(d.get('proponent_name', 'Grupo Acacia'))}}}\n"
        f"\\newcommand{{\\proponentcontact}}{{{_e(d.get('proponent_contact', ''))}}}\n"
        f"\\newcommand{{\\proponentaddress}}{{{_e(d.get('proponent_address', ''))}}}\n"
        f"\\newcommand{{\\proponentemail}}{{{_e(d.get('proponent_email', ''))}}}\n"
        f"\\newcommand{{\\proponentphone}}{{{_e(d.get('proponent_phone', ''))}}}\n"
        f"\\newcommand{{\\proponentwebsite}}{{{_e(d.get('proponent_website', ''))}}}\n"
        f"\\newcommand{{\\proposalref}}{{{_e(d.get('proposal_ref', ''))}}}\n"
        f"\\newcommand{{\\proposaldate}}{{{_e(d.get('proposal_date', ''))}}}\n"
        f"\\newcommand{{\\proposalversion}}{{{_e(d.get('proposal_version', 'ver. 1.0'))}}}\n"
        "\\newcommand{\\logocount}{1}\n"
        "\\newcommand{\\logoone}{docs/logo-dark}\n"
        "\\newcommand{\\logotwo}{docs/logo-light}\n"
        f"\\newcommand{{\\partnercount}}{{{_e(d.get('partner_count', '0'))}}}\n"
        f"\\newcommand{{\\partnername}}{{{_e(d.get('partner_name', ''))}}}\n"
        f"\\newcommand{{\\partnercontact}}{{{_e(d.get('partner_contact', ''))}}}\n"
        f"\\newcommand{{\\partneraddress}}{{{_e(d.get('partner_address', ''))}}}\n"
        f"\\newcommand{{\\partneremail}}{{{_e(d.get('partner_email', ''))}}}\n"
        f"\\newcommand{{\\partnerphone}}{{{_e(d.get('partner_phone', ''))}}}\n"
        "\\newcommand{\\partnerlogo}{}\n"
        f"\\newcommand{{\\currency}}{{{_e(d.get('currency', '€'))}}}\n"
    )


def _save_images(images: list, work_dir: Path) -> list[tuple[str, str]]:
    """Decode base64 images, write to work_dir, return [(filename, caption)]."""
    saved = []
    for i, img in enumerate(images):
        ext = _MIME_EXT.get(img.get("mime_type", "image/jpeg"), "jpg")
        filename = f"web-img-{i:02d}.{ext}"
        raw = img.get("data", "")
        if "," in raw:
            raw = raw.split(",", 1)[1]
        (work_dir / filename).write_bytes(base64.b64decode(raw))
        saved.append((filename, img.get("caption", "")))
    return saved


def _images_latex(saved: list[tuple[str, str]]) -> str:
    if not saved:
        return ""

    lines = ["\\subsection*{Galeria de Imagens}\n"]

    i = 0
    while i < len(saved):
        fn1, cap1 = saved[i]
        if i + 1 < len(saved):
            fn2, cap2 = saved[i + 1]
            lines.append(
                "\\noindent\n"
                "\\begin{minipage}[t]{0.48\\linewidth}\n"
                f"  \\includegraphics[width=\\linewidth,height=6cm,keepaspectratio]{{{fn1}}}\n"
                f"  \\captionof{{figure}}{{{_e(cap1)}}}\n"
                "\\end{minipage}\n"
                "\\hfill\n"
                "\\begin{minipage}[t]{0.48\\linewidth}\n"
                f"  \\includegraphics[width=\\linewidth,height=6cm,keepaspectratio]{{{fn2}}}\n"
                f"  \\captionof{{figure}}{{{_e(cap2)}}}\n"
                "\\end{minipage}\n\n"
                "\\vspace{0.8em}\n"
            )
            i += 2
        else:
            lines.append(
                "\\begin{center}\n"
                f"  \\includegraphics[width=0.75\\linewidth,height=8cm,keepaspectratio]{{{fn1}}}\n"
                f"  \\captionof{{figure}}{{{_e(cap1)}}}\n"
                "\\end{center}\n\n"
            )
            i += 1

    return "\n".join(lines)


def _products_latex(products: list, currency: str, tax_rate: float) -> str:
    if not products:
        return ""

    subtotal = sum(p.get("price", 0) * p.get("quantity", 1) for p in products)
    tax_amount = subtotal * tax_rate / 100
    grand_total = subtotal + tax_amount

    rows = []
    for idx, p in enumerate(products):
        line_total = p.get("price", 0) * p.get("quantity", 1)
        color = "\\rowcolor{doc-cream}" if idx % 2 == 0 else ""
        rows.append(
            f"{color}"
            f"  {_e(p.get('name', ''))} & "
            f"  {_fmt_money(p.get('price', 0), currency)} & "
            f"  {_fmt_qty(p.get('quantity', 1))} & "
            f"  {_fmt_money(line_total, currency)} \\\\"
        )

    tax_row = ""
    if tax_rate > 0:
        tax_row = (
            f"  \\multicolumn{{3}}{{r}}"
            f"{{\\sffamily\\small IVA ({tax_rate:g}\\%)}} & "
            f"{_fmt_money(tax_amount, currency)} \\\\\n"
        )

    return (
        "\\subsection{Produtos e Serviços}\n\n"
        "\\begin{tabularx}{\\linewidth}{Xrrr}\n"
        "\\hline\n"
        "\\rowcolor{doc-navy}\n"
        "  \\textcolor{white}{\\bfseries\\sffamily Descrição} &\n"
        "  \\textcolor{white}{\\bfseries\\sffamily Preço Unit.} &\n"
        "  \\textcolor{white}{\\bfseries\\sffamily Qtd.} &\n"
        "  \\textcolor{white}{\\bfseries\\sffamily Total} \\\\\n"
        "\\hline\n"
        + "\n".join(rows) + "\n"
        "\\hline\n"
        f"  \\multicolumn{{3}}{{r}}{{\\sffamily\\small Subtotal}} & "
        f"{_fmt_money(subtotal, currency)} \\\\\n"
        + tax_row
        + "\\hline\n"
        f"  \\multicolumn{{3}}{{r}}{{\\bfseries\\sffamily Total}} & "
        f"\\bfseries {_fmt_money(grand_total, currency)} \\\\\n"
        "\\hline\n"
        "\\end{tabularx}\n"
    )


def _section_tex(title: str, content: str) -> str:
    return f"% Generated by proposal-web\n\\section{{{title}}}\n\n{content}\n"


def compile_proposal(data: dict, content: dict) -> bytes:
    currency = data.get("currency", "€")

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "proposal"
        shutil.copytree(PROPOSAL_SRC, work, ignore=shutil.ignore_patterns("build"))
        (work / "build").mkdir()

        (work / "business-proposal-info.tex").write_text(
            _info_tex(data), encoding="utf-8"
        )

        # Save uploaded images and build their LaTeX block
        saved_images = _save_images(data.get("images", []), work)
        images_block = _images_latex(saved_images)

        # Build products table LaTeX
        products_block = _products_latex(
            data.get("products", []), currency, data.get("tax_rate", 0.0)
        )

        for key, latex in content.items():
            body = latex
            if key == "solution" and images_block:
                body = body + "\n\n" + images_block
            if key == "investment" and products_block:
                body = body + "\n\n" + products_block
            (work / "content" / _SECTION_FILES[key]).write_text(
                _section_tex(_SECTION_TITLES[key], body), encoding="utf-8"
            )

        cmd = [
            "lualatex",
            "-interaction=nonstopmode",
            "-output-directory=build",
            "business-proposal.tex",
        ]
        for _ in range(2):
            subprocess.run(cmd, cwd=str(work), capture_output=True)

        pdf = work / "build" / "business-proposal.pdf"
        if not pdf.exists():
            log_path = work / "build" / "business-proposal.log"
            if log_path.exists():
                lines = log_path.read_text(errors="ignore").splitlines()
                # Extract error lines + 4 lines of context after each
                error_lines = []
                for i, line in enumerate(lines):
                    if line.startswith("!") or "LaTeX Error" in line or "Fatal error" in line:
                        error_lines.extend(lines[i : i + 5])
                        error_lines.append("---")
                excerpt = "\n".join(error_lines) if error_lines else "\n".join(lines[-60:])
            else:
                excerpt = "no log produced"
            raise RuntimeError(f"lualatex failed.\n\n{excerpt}")

        return pdf.read_bytes()
